spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PWD}
    jpa:
        database: postgresql
        generate-ddl: true
        properties:
            hibernate:
                default_schema: "music_bands_service"
    sql:
        init:
            mode: always

    application:
        name: music-bands-service
#    cloud:
#        consul:
#            host: localhost
#            port: 8500
#            discovery:
#                health-check-tls-skip-verify: true
#                health-check-url: https://localhost:${server.port}/actuator/health

springdoc:
    swagger-ui:
        disable-swagger-default-url: true
        path: /docs
    default-produces-media-type: "application/json"
    default-consumes-media-type: "application/json"

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-password: password
        key-store-type: PKCS12
        key-alias: bands
